const users = [
  {
    id: 1,
    name: 'John',
    email: 'john@gmail.com',
  },
  {
    id: 2,
    name: 'Smith',
    email: 'smith@gm.com',
  },
  {
    id: 3,
    name: 'Jane',
    email: 'jane@gm.cim',
  },
];

const DUMMY_PURCHASE_REQUEST = {
  status: 'success',
  data: {
    notice: null,
    id: 'a6334dd4-4c5a-46c4-b98b-df7c2917aa8d',
    identifier: 'PR2013',
    accordion_api:
      '/purchase_requests/a6334dd4-4c5a-46c4-b98b-df7c2917aa8d/accordion_view',
    status: {
      id: 'draft',
      presentation: 'Draft',
    },
    type: 'Requested by me',
    total_value: 'RM46,900.00',
    created_at: 'Dec 27 2023',
    submitted_at: null,
    discarded_at: null,
    purchase_reason: null,
    po_ids: [],
    created_by: {
      id: '57a8aa6a-7f4a-4c9b-8ecd-1fff75d4f3ac',
      presentation: 'AM1',
      email: 'rahul+10@zapro.ai',
    },
    requested_by: {
      id: '57a8aa6a-7f4a-4c9b-8ecd-1fff75d4f3ac',
      presentation: 'AM1',
      email: 'rahul+10@zapro.ai',
    },
    actions: {
      primary_actions: [
        {
          type: 'save',
          label: 'Save',
          url: '/purchase_requests/a6334dd4-4c5a-46c4-b98b-df7c2917aa8d/save',
          method: 'post',
          button_type: 'secondary',
          disabled: false,
          confirmation_modal: null,
          redirect: false,
          redirect_url: null,
          show_rejection_modal: null,
        },
        {
          type: 'submit',
          label: 'Submit',
          url: '/purchase_requests/a6334dd4-4c5a-46c4-b98b-df7c2917aa8d/submit',
          method: 'post',
          button_type: 'primary',
          disabled: false,
          confirmation_modal: true,
          redirect: true,
          redirect_url: null,
          show_rejection_modal: null,
          action_status_modal: true,
          action_popup_keys: {
            popup_type: 'success',
            popup_title: 'Purchase Requisition #PR2013',
            popup_subtitle: 'has been successfully submitted',
            popup_button_text: 'View #PR2013',
            popup_button_type: 'primary',
            popup_redirect_url:
              '/purchase-request/a6334dd4-4c5a-46c4-b98b-df7c2917aa8d/edit',
          },
          modal_type: 'warning',
          confirmation_modal_message:
            'You have the following warning message: High value order, please confirm with your manager once. Are you sure you want to continue?',
          confirmation_modal_title: 'Warning Message',
        },
      ],
      secondary_actions: [
        {
          type: 'duplicate',
          label: 'Duplicate',
          url: '/purchase_requests/a6334dd4-4c5a-46c4-b98b-df7c2917aa8d/duplicate',
          method: 'post',
          button_type: 'secondary',
          disabled: false,
          confirmation_modal: null,
          redirect: true,
          redirect_url: null,
          show_rejection_modal: null,
        },
        {
          type: 'discard',
          label: 'Discard',
          url: '/purchase_requests/a6334dd4-4c5a-46c4-b98b-df7c2917aa8d/discard',
          method: 'post',
          button_type: 'secondary',
          disabled: false,
          confirmation_modal: true,
          redirect: true,
          redirect_url: '/purchase-request',
          show_rejection_modal: null,
          confirmation_modal_message: 'Are you sure you want to discard?',
          modal_type: 'confirmation',
        },
      ],
    },
    show_add_row: true,
    show_add_non_catalog_items: true,
    show_add_item_master: true,
    show_bulk_edit: true,
    general_info: [
      {
        presentation: 'General Info',
        fields: [
          {
            id: '286513a9-de5c-46ed-88d2-db9015a4eb37',
            type: 'date',
            label: 'Date of creation',
            is_editable: true,
            is_hidden: false,
            is_required: false,
            value: '2023-12-27',
            value_presentation: 'Dec 27 2023',
            callback_dependent_field_ids: [],
          },
          {
            id: '640c9550-5141-46bd-8933-b7b262982c88',
            type: 'text',
            label: 'Copied from',
            is_editable: false,
            is_hidden: false,
            is_required: false,
            value: null,
            value_presentation: null,
            callback_dependent_field_ids: [],
          },
          {
            id: '048dfbd9-b589-45a8-a0a3-66befa44d231',
            type: 'dynamic_dropdown',
            label: 'Requesting for',
            is_editable: true,
            is_hidden: false,
            is_required: false,
            value: '57a8aa6a-7f4a-4c9b-8ecd-1fff75d4f3ac',
            value_presentation: 'AM1',
            callback_dependent_field_ids: [],
            options: [
              {
                value: '7f87fc8a-b498-47e4-9378-1b33d7aeb4d9',
                label: 'AM07',
              },
              {
                value: 'ec43caaf-3f57-4d0e-bdea-04d908205f93',
                label: 'john_doe 2',
              },
              {
                value: '57a8aa6a-7f4a-4c9b-8ecd-1fff75d4f3ac',
                label: 'AM1',
              },
            ],
          },
          {
            id: '46b500da-c825-4c66-aeae-4dcda8f36f62',
            type: 'dynamic_dropdown',
            label: 'Created by',
            is_editable: false,
            is_hidden: false,
            is_required: false,
            value: '57a8aa6a-7f4a-4c9b-8ecd-1fff75d4f3ac',
            value_presentation: 'AM1',
            callback_dependent_field_ids: [],
            options: [
              {
                value: '7f87fc8a-b498-47e4-9378-1b33d7aeb4d9',
                label: 'AM07',
              },
              {
                value: 'ec43caaf-3f57-4d0e-bdea-04d908205f93',
                label: 'john_doe 2',
              },
              {
                value: '57a8aa6a-7f4a-4c9b-8ecd-1fff75d4f3ac',
                label: 'AM1',
              },
            ],
          },
          {
            id: '81fc601c-efe8-4c5e-ac61-e384804e90da',
            type: 'attachment',
            label: 'Attachment',
            is_editable: true,
            is_hidden: false,
            is_required: false,
            value: null,
            value_presentation: [],
            callback_dependent_field_ids: [],
          },
          {
            id: '9eb9f6b5-c15f-4dbb-bf94-c492b2bfe65a',
            type: 'refreshing_radio',
            label: 'Ship to type',
            is_editable: true,
            is_hidden: false,
            is_required: false,
            value: 'header_level',
            value_presentation: 'Header Level',
            callback_url: '/refreshing_fields/refresh',
            callback_dependent_field_ids: [],
            options: [
              {
                value: 'header_level',
                label: 'Header Level',
              },
              {
                value: 'item_level',
                label: 'Item Level',
              },
            ],
          },
          {
            id: '5833ab6a-e94b-4e9a-8191-ca9783035e4c',
            type: 'dynamic_dropdown',
            label: 'Ship to address',
            is_editable: true,
            is_hidden: false,
            is_required: false,
            value: '8ff7eb73-3a15-4a2b-8366-c690ea687057',
            value_presentation: 'Office Address',
            callback_dependent_field_ids: [],
            options: [
              {
                value: '8ff7eb73-3a15-4a2b-8366-c690ea687057',
                label: 'Office Address',
              },
              {
                value: 'c629e2f7-f4f8-46b7-aa6e-f459c70dda11',
                label: 'Uthistan ',
              },
              {
                value: 'f916dede-fbc6-4d52-8280-c5c1989c1b84',
                label: '2qweqqw',
              },
              {
                value: '11c3dbcc-4ae3-4d17-82d5-a05f0a1c4ed3',
                label: 'Donovan',
              },
              {
                value: 'c0331897-5587-4106-a4cc-b6978c64919e',
                label: 'Chennai Office1',
              },
              {
                value: '28e4089f-4e5b-4d27-8153-a64857c1740e',
                label: 'Test',
              },
              {
                value: 'b1b2261a-6e30-4c6d-9edc-3d9ae8cf9ea0',
                label: 'Unknown test',
              },
              {
                value: '753e9d03-ba79-4f63-85fd-039f643cf8a9',
                label: 'test111',
              },
            ],
          },
          {
            id: 'f86f7bd7-1e08-4bcb-b899-a9471b053cd6',
            type: 'multi_line_text',
            label: 'Purchase reason',
            is_editable: true,
            is_hidden: false,
            is_required: false,
            value: null,
            value_presentation: null,
            callback_dependent_field_ids: [],
          },
          {
            id: '684b400c-bd47-479f-8f29-17e0df11032a',
            type: 'attachment',
            label: 'Att',
            is_editable: true,
            is_hidden: false,
            is_required: true,
            value: null,
            value_presentation: [],
            callback_dependent_field_ids: [],
          },
          {
            id: '102faa62-3fad-4e37-9730-7d24775192ec',
            type: 'text',
            label: 'test new update api',
            is_editable: true,
            is_hidden: false,
            is_required: false,
            value: null,
            value_presentation: null,
            callback_dependent_field_ids: [],
          },
          {
            id: '3f58e603-f78a-490e-8e8b-3f439321fffd',
            type: 'text',
            label: 'Re invoice to customers',
            is_editable: true,
            is_hidden: false,
            is_required: false,
            value: null,
            value_presentation: null,
            callback_dependent_field_ids: [],
          },
        ],
      },
    ],
    line_items_tables: [
      {
        table_title: 'Lines',
        view_mode: 'card',
        table_data: [
          {
            id: '16a137cb-ffd0-46fa-b367-54c0bdb8d6b5',
            index: 1,
            item_type: {
              id: '57a8c59e-45d8-4a38-8dfa-7d3242e88166',
              value: 'goods',
              value_presentation: 'Goods',
              is_editable: false,
              tooltip: null,
              type: 'dropdown',
            },
            item: {
              id: 'c6dc7089-1a88-443b-9cfd-c4c0c8b5355d',
              value: 'Office Chair',
              value_presentation: 'Office Chair',
              is_editable: true,
              tooltip: null,
              type: 'string',
            },
            quantity: {
              id: 'eff2a763-7087-46fe-827d-4de6d979f6a6',
              value: 1,
              value_presentation: 1,
              is_editable: true,
              tooltip: null,
              type: 'number',
            },
            unit_of_measure: {
              id: '538409f1-d00f-450d-bdbe-8a3f90847f76',
              value: 'e00347a8-64bc-4e50-85e2-7844d5912fb8',
              value_presentation: 'M',
              is_editable: false,
              tooltip: null,
              type: 'string',
            },
            total: {
              id: '225f8d42-4a28-4e7b-94fc-46250f26e4fb',
              value: 5000,
              value_presentation: '$5,000.00',
              is_editable: false,
              tooltip: 'RM23,450.00',
              type: 'number',
            },
          },
          {
            id: 'ff977981-5178-49f3-af0b-feaa8da5255a',
            index: 2,
            item_type: {
              id: '7d7b036f-e54d-4af7-ab84-d9b6f4a3a5c0',
              value: 'goods',
              value_presentation: 'Goods',
              is_editable: false,
              tooltip: null,
              type: 'dropdown',
            },
            item: {
              id: 'c2d19191-aff4-4b42-8d9c-728e9e6f98ac',
              value: 'A Ruler',
              value_presentation: 'A Ruler',
              is_editable: false,
              tooltip: null,
              type: 'string',
            },
            quantity: {
              id: 'f7e64e88-ee8d-4cfd-a649-582683eae3b5',
              value: 1,
              value_presentation: 1,
              is_editable: true,
              tooltip: null,
              type: 'number',
            },
            unit_of_measure: {
              id: 'c1627ef2-4be4-4ea2-9244-93d2e2f24e2a',
              value: 'e00347a8-64bc-4e50-85e2-7844d5912fb8',
              value_presentation: 'M',
              is_editable: false,
              tooltip: null,
              type: 'string',
            },
            total: {
              id: 'e18e6800-f070-411d-91fc-345d14005599',
              value: 5000,
              value_presentation: '$5,000.00',
              is_editable: false,
              tooltip: 'RM23,450.00',
              type: 'number',
            },
          },
        ],
        table_meta: [
          {
            title: '#',
            data_index: 'index',
          },
          {
            title: 'Item Type',
            data_index: 'item_type',
          },
          {
            title: 'Item',
            data_index: 'item',
          },
          {
            title: 'Qty',
            data_index: 'quantity',
          },
          {
            title: 'UOM',
            data_index: 'unit_of_measure',
          },
          {
            title: 'Total',
            data_index: 'total',
          },
        ],
      },
    ],
  },
};

module.exports = { users, DUMMY_PURCHASE_REQUEST };
